# I tried to user docker, but everytime I updated something it was necessary to
# build it again, so I gave up. I tried use volume a little bit, but without success

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000